import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { WalletProvider } from "@/lib/wallet";
import { ToastProvider } from "@/lib/toast";
import { SiteHeader } from "@/components/SiteHeader";
import { SiteFooter } from "@/components/SiteFooter";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  preload: true,
});

function siteOrigin(): string {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "");
  if (explicit) return explicit;
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL.replace(/\/$/, "")}`;
  return "http://localhost:3000";
}

const title = "Unipad — Launch & mint NFTs on Unicity";
const description =
  "Create a drop or mint an NFT with UCT. Fair minting on Unicity — no gas wars.";

export const metadata: Metadata = {
  metadataBase: new URL(siteOrigin()),
  title,
  description,
  applicationName: "Unipad",
  keywords: ["Unipad", "Unicity", "UCT", "NFT", "launchpad", "Sphere"],
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    apple: [{ url: "/apple-icon", sizes: "180x180", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "Unipad",
    title,
    description,
    // Generated by src/app/opengraph-image.tsx (includes hero character)
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
    // Generated by src/app/twitter-image.tsx
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <ToastProvider>
          <WalletProvider>
            <SiteHeader />
            <main>{children}</main>
            <SiteFooter />
          </WalletProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
